# Generated by Django 5.1.4 on 2024-12-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echipamente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echipaement',
            old_name='ip_adresa',
            new_name='ip',
        ),
    ]
