# Generated by Django 5.1.4 on 2024-12-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echipamente', '0002_rename_ip_adresa_echipaement_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echipament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch')], max_length=50)),
                ('nume', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('utilizator', models.CharField(max_length=50)),
                ('parola', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InterfataRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_interfata', models.CharField(max_length=50, verbose_name='Numele Interfetei')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresa IP')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, verbose_name='Numele Routerului')),
                ('ip_mgmt', models.GenericIPAddressField(verbose_name='IP Management')),
            ],
        ),
        migrations.DeleteModel(
            name='Echipaement',
        ),
        migrations.AddField(
            model_name='interfatarouter',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfete', to='echipamente.router', verbose_name='Router'),
        ),
    ]
