# Generated by Django 5.1.4 on 2024-12-28 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echipamente', '0003_echipament_interfatarouter_router_delete_echipaement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='echipament', to='echipamente.echipament', verbose_name='Router'),
        ),
    ]
